name: First workflow
on: workflow_disptch
jobs:
   first-job:
       runs-on: ubuntu-latest
       steps:
           - name: Print Greetings
             run: echo "Hello World"

           - name: Print Goodbye
             run: |
              echo "This is my first git hug action"
              echo "Workflow executed sucessfully"
